workflows:
  ios_build:
    name: Build Coffee App iOS — Рабочая версия 2025
    max_build_duration: 120
    instance_type: mac_mini_m2                     # Самый стабильный и быстрый
    environment:
      flutter: stable
      xcode: latest                                 # Всегда свежий Xcode
      cocoapods: default
      groups:
        - apple_credentials                         # ← Добавь сюда свой Apple ID / сертификаты

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '**'
          include: true
          source: true

    # Отключаем кэш — он часто ломает iOS-сборку после правок pubspec.yaml и Podfile
    cache:
      disabled: true

    scripts:
      # 1. Полная очистка перед сборкой — КРИТИЧНО!
      - name: Flutter Clean + Pub Get
        script: |
          flutter clean
          flutter pub get

      # 2. Удаляем старые проблемные файлы
      - name: Удаляем Generated.xcconfig и кэш CocoaPods
        script: |
          rm -f ios/Flutter/Generated.xcconfig
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -f ios/Podfile.lock

      # 3. Устанавливаем поды с полной переустановкой
      - name: Pod Install (с принудительным обновлением)
        script: |
          cd ios
          pod repo update || true
          pod install --repo-update

      # 4. Сборка .ipa с кодсайном (обязательно для установки!)
      - name: Build iOS IPA (с кодсайном!)
        script: |
          flutter build ios --release
          # Если используешь автоматическую подпись в Codemagic — оставь так:
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios.xcarchive \
                     -allowProvisioningUpdates \
                     archive
          xcodebuild -archivePath build/ios.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath build/ipa \
                     -allowProvisioningUpdates \
                     exportArchive

    artifacts:
      - build/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - mayklmaykl98@mail.ru
        notify:
          success: true
          failure: true
      slack:
        channel: "#flutter-builds"
        notify_on_build_start: false

      # Автоматическая загрузка в Diawi (чтобы сразу получить ссылку на установку)
      scripts:
        - name: Загрузка на Diawi.com (ссылка придёт на почту)
          script: |
            curl "https://upload.diawi.com/" \
              -F token="ТВОЙ_ТОКЕН_DIAWI_ЗДЕСЬ" \
              -F file=@build/ipa/*.ipa \
              -F find_by_udid=0 \
              -F comment="Coffee App — автосборка Codemagic" | jq -r '.link' | tee diawi_link.txt
            echo "Ссылка на установку: $(cat diawi_link.txt)"