workflows:
  ios_build:
    name: Build Coffee App iOS
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '**'
          include: true

    cache:
      cache_paths:
        - ios/Pods
        - .pub-cache
        - $HOME/.cocoapods/repos

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install iOS pods
        script: |
          cd ios
          pod repo update
          pod install --repo-update

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - mayklmaykl98@mail.ru
        notify:
          success: true
          failure: true